apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-actions-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner
      terminationGracePeriodSeconds: 30
      containers:
        - name: runner
          image: partofaplan/github-actions-runner-java:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "/runner/runner-entrypoint.sh"]
          env:
            - name: GITHUB_OWNER
              value: "partofaplan"
            - name: GITHUB_REPOSITORY
              value: "sample-java-application"
            - name: RUNNER_LABELS
              value: "self-hosted,kubernetes,local,alpha"
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
            - name: RUNNER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: github-runner-secret
                  key: GITHUB_PAT
          volumeMounts:
            - name: runner-scripts
              mountPath: /runner/runner-entrypoint.sh
              subPath: runner-entrypoint.sh
            - name: runner-work
              mountPath: /actions-runner/_work
            - name: docker-sock
              mountPath: /var/run
          resources:
            requests:
              cpu: "500m"
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 4Gi
        - name: dind
          image: docker:25.0.5-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          args:
            - --host=tcp://0.0.0.0:2375
            - --host=unix:///var/run/docker.sock
            - --storage-driver=overlay2
          volumeMounts:
            - name: docker-graph
              mountPath: /var/lib/docker
            - name: docker-sock
              mountPath: /var/run
      volumes:
        - name: runner-scripts
          configMap:
            name: github-runner-scripts
            defaultMode: 0755
        - name: runner-work
          emptyDir: {}
        - name: docker-graph
          emptyDir: {}
        - name: docker-sock
          emptyDir: {}
