apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-actions-runner

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml

configMapGenerator:
  - name: github-runner-scripts
    files:
      - runner-entrypoint.sh=scripts/runner-entrypoint.sh
    options:
      disableNameSuffixHash: true
